### ISSUE TITLE
Migrate to API v4

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#1]
This issue is here to let you know that we are commited to maintaining this project and I will make this migration soon. So you don't have to worry that gitlabform will stop working with subsequent GitLab versions. :) Also please note that API v3 did not go away in 9.5 (http://disq.us/p/1lky6q4) and will not go away soon, so there is no rush with this. See https://gitlab.com/gitlab-org/gitlab-ce/issues/36819 for details.

**Comment by born4new** [comment]
Now that the API v3 has been removed, I believe it would be time to tackle this issue?

We just migrated to `Gitlab 11.0.1` and gitlabform is currently unusable.

Let me know if I can help.

**Comment by gdubicki** [comment]
Hi @born4new, thanks for letting me know. I start 2 weeks vacation without a computer in a week so if you need v4 support badly then creating a PR this week would help. If you could migrate at least part of the code it would be very helpful. Ping me on gitter if want to talk about it.

**Comment by gdubicki** [comment]
The way I see it we will can leave v3 behind, pointing to existing latest gitlabform for users of GitLab <11, and replace all v3 calls with v4 ones.

**Comment by born4new** [comment]
Hey there!

Bad timing I must say, as I'm also going on vaca starting tonight...

Personally, not a massive rush to get this one done :).

We'll see who's the first one to work on it then 😆

**Comment by nomadme** [comment]
Any update on the migration?
