### ISSUE TITLE
Enforcing project members

### ISSUE THREAD

**Issue by sgraca** [egnyte/gitlabform#100]
Hi,

It would be nice to have a feature similar to `enforce_group_members` also for direct project members. That would allow to have full control (and auditing) of who has access to a project.

Is there a particular reason why it was only implemented for groups and not for projects?

**Comment by gdubicki** [comment]
Thanks for asking!

No, it was just that someone needed it for groups and created a PR for it, IIRC.

With the group membership enforcement as an example it should be easy to add though.

We are to a PR with such addition.

**Comment by sgraca** [comment]
Unfortunately I don't have the capacity to look into this at the moment, but hopefully I'll go back to this in a couple of months.

**Comment by gdubicki** [comment]
Implemented and released in v2.8.0. Please check it out and let us know what you think, @sgraca ! :)
