### ISSUE TITLE
Multiple email notifications when adding members to project

### ISSUE THREAD

**Issue by sgraca** [egnyte/gitlabform#101]
GitLabForm when assigns users to project first removes a user from the project and then adds it with desired access level. This causes that each user configured in GitLabForm is notified about an access being granted to a project each time GitLabForm is executed.
This can become really inconvenient if GitLabForm is used to enforce settings on multiple projects and run automatically (for example on a daily basis).

**Comment by gdubicki** [comment]
Thanks for reporting the issue!

That’s a valid point, GitLabForm should not generate those notifications.

It’s an easy fix, good for the first PR. Do you want to implement it yourself, @sgraca ?

**Comment by sgraca** [comment]
Unfortunately I don't have the capacity to look into this at the moment, but hopefully I'll get back to this in a couple of months.

**Comment by amimas** [comment]
I'm starting to run into this now.

> It’s an easy fix, good for the first PR

@gdubicki - can you give me some hints on where to start? I might take a stab if I have time. This seems similar to branch protection issue: first remove and then add. I think we need to check if the user is already added with the configured setting.

**Comment by gdubicki** [comment]
Thanks @amimas ! I think that what we need is to expand the current naive code here https://github.com/egnyte/gitlabform/blob/b1538152cae040a0475779c258ff6071e8a5e175/gitlabform/gitlabform/processors/project/members_processor.py#L26-L29 and here https://github.com/egnyte/gitlabform/blob/b1538152cae040a0475779c258ff6071e8a5e175/gitlabform/gitlabform/processors/project/members_processor.py#L43-L46 to check the current access level and do nothing if it's not changed.

But we should have a lot if tests for this as reading my commit message from https://github.com/egnyte/gitlabform/commit/0bc88f4d3a43d20d719b4d030f4516eee7c924dd I see that there are some edge cases lurking here.

**Comment by amimas** [comment]
Thanks @gdubicki . I'll see if I can make some time soon for this fix.

**Comment by gdubicki** [comment]
Please make PR to branch v2, @amimas . We will release v2 very soon, there is no point in working on v1 anymore.

**Comment by gdubicki** [comment]
v2 final has been released. Please reopen this ticket if you still have issues.

**Comment by amimas** [comment]
I didn't get a chance work on this but so happy to see that this has been addressed in v2. Now I really need to upgrade. 😅
