### ISSUE TITLE
Add delete variable action

### ISSUE THREAD

**Issue by ss7548** [egnyte/gitlabform#110]
Provide a method to delete secret variables from groups and projects
https://docs.gitlab.com/ee/api/project_level_variables.html#remove-variable
https://docs.gitlab.com/ee/api/group_level_variables.html#remove-variable

**Comment by gdubicki** [comment]
Thanks @ss7548 ! Please see my review in the PR above.

**Comment by gdubicki** [comment]
Added in v1.15.4.1 that has just been released (v.1.15.4 was not released as its build has failed). Thanks @ss7548 !
