### ISSUE TITLE
Is it possible to change timeout ?

### ISSUE THREAD

**Issue by grzesuav** [egnyte/gitlabform#124]
We are hitting regular timeout on some operations, is it possible to configure it ?

**Comment by gdubicki** [comment]
Hey, no, but.. You know. ;D

**Comment by gdubicki** [comment]
There is a single method that is used for all the HTTP requests, so this is easy to implement.

**Comment by grzesuav** [comment]
https://github.com/egnyte/gitlabform/pull/127

**Comment by gdubicki** [comment]
Released in v.1.17.0.1 (1.17.0 also, but that version didn't release docker images correctly). Thanks for the contribution @grzesuav ! 👍
