### ISSUE TITLE
ssl_verify=false is too verbose

### ISSUE THREAD

**Issue by pijoter** [egnyte/gitlabform#134]
setting `ssl_verify: false` in config file cause every rest api call to print warning message
maybe such message should be printed only once?

```
/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'hostname'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

**Comment by gdubicki** [comment]
Plese see https://github.com/egnyte/gitlabform/issues/133#issuecomment-723661274 , @pijoter . :)
