### ISSUE TITLE
bug(pipeline_schedules) - Unexpected return code 202 on delete

### ISSUE THREAD

**Issue by grzesuav** [egnyte/gitlabform#148]
`
gitlabform.gitlab.core.UnexpectedResponseException: Request url='some_url/pipeline_schedules/1875/variables/SCHEDULE', method=DELETE, data='None' failed - expected code(s) [200, 201, 204, 404], got code 202 & body: 'b'{"variable_type":"env_var","key":"somekey","value":"somevalue"}''
`

**Comment by grzesuav** [comment]
https://github.com/egnyte/gitlabform/pull/149

**Comment by kowpatryk** [comment]
PR has been merged. I will close the ticket as soon as the fix gets rolled out in the next release.

**Comment by gdubicki** [comment]
Technically fixed in v.1.19.0 but the first PyPI+DockerHub images release with this is v.1.20.0.
