### ISSUE TITLE
Provide some project name and group as built-in variables that you could use in the config

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#15]
As suggested #6 it would be good to be able to reference the name of currently processed project 
and group in its config.

### Use case example

Let's assume that you have bunch of custom Puppet modules without `metadata.json`. You don't need this file for the modules to work, but you need it to start testing them with https://github.com/puppetlabs/pdk and for full Puppet support in some IDEs (like IntelliJ - https://plugins.jetbrains.com/plugin/7180-puppet-support?#comment=24765).

To add this `metadata.json` with gitlabform, after this issue would be resolved, you could use this as a `metadata.json` template in `files` section:

```
{
  "name": "company-{{ project }}",
  "version": "1.0.0",
  "summary": "{{ project }}",
  "license": "proprietary",
  "source": "https://git.company.com/{{ group }}/{{ project }}",
  "project_page": "https://git.company.com/{{ group }}/{{ project }}/tree/master",
  "dependencies": [
  ],
  "operatingsystem_support": [
    {
      "operatingsystem": "CentOS",
      "operatingsystemrelease": [
        "7"
      ]
    }
  ],
  "requirements": [
    {
      "name": "puppet",
      "version_requirement": ">= 4.7.0 < 6.0.0"
    }
  ],
  "pdk-version": "1.2.0",
  "template-url": "file:///opt/puppetlabs/pdk/share/cache/pdk-module-template.git",
  "template-ref": "heads/master-0-g3f7d5ce"
}
```

..where all occurrences of `{{ project }}` would be replaced with current project name and `{{ group }}` - with group name.

UPDATED: switched to Jinja2-like syntax.

**Comment by gdubicki** [comment]
Implemented in https://github.com/egnyte/gitlabform/releases/tag/v0.22.0 .

**Comment by weakcamel** [comment]
@gdubicki  I struggle with using this feature for MR approvals; namely, I'm trying to add the group X to the approvers group for each processed project.

And I wonder, perhaps I misunderstood how this works? Are the tokens (project/group) supported generally in the YAML syntax or is it something used internally in GitlabForm while generating the JSON or with `files` only?

**Comment by weakcamel** [comment]
OK, I think I found the answer after browsing the code where this feature was introduced: tokens substitution is only performed while generating output files.

https://github.com/egnyte/gitlabform/compare/v0.21.2...v0.22.0

That's fair enough.. :) I was just hoping to use it to assign `approver_groups` and exploring whether this templating is powerful enough to inject extra content, e.g. secrets like passwords/API keys which I keep in [Hashicorp Vault](https://www.vaultproject.io/).

**Comment by gdubicki** [comment]
Yes, templating works only for files added/updated to managed repositories.
