### ISSUE TITLE
Enforce group sharing

### ISSUE THREAD

**Issue by amimas** [egnyte/gitlabform#150]
I need to set up a group to be shared with another group. For example, a groupP1 containing projects will be shared with groupU1. This seems doable but if I manually share groupP1 with groupU2, gitlabform doesn't remove that manual share even if I have the enforcement option enabled. I think this is because the enforcement option currently enforces members but not the shared groups.

Can the permission enforcement option for groups be enhanced so that group sharing is enforced also?

**Comment by gdubicki** [comment]
Hi @amimas ! I think that it can be done and we are open to PRs with this extra feature. :)

**Comment by amimas** [comment]
So many cool features going into v2. Can't wait to upgrade and take advantage of these features.

Thanks for looking into this request.
