### ISSUE TITLE
Migrate from Travis CI to something else for testing, building and releasing

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#156]
Because Travis has de facto killed the free plan for open source projects, we need to migrate to a different solution.

I think that GitHub Actions would be nice, I plan to check it out within the next few days.

**Comment by amimas** [comment]
Just out of curiosity, any reason why this project is not in gitlab.com or is not being considered? You get the integrated CI solution along with all the other features; and since it's an open source project, you'll also get all the features of Enterprise edition. I think that would be useful for testing features that are not available in CE edition. You can still have a mirror in github.com, if needed.

**Comment by weakcamel** [comment]
That's interesting; where was it announced?

https://www.travis-ci.com/ still claims the following:

> Testing your open source projects is always 100% free!

and there's still the Free Plan listed on https://www.travis-ci.com/plans

**Comment by gdubicki** [comment]
[Here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), @weakcamel .

But while making old plan not work anymore has been implemented, thew new plans are not.

GitLabForm's Travis CI page says:
> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

...and both links in this message lead to a page with "There was an error, please try again." error. (Of course I did try again - to no avail.)

When I asked their support for help and got this in response:
> Our OSS/Education plans are under review and not available at the moment. We will communicate to customers once these plans are available again. 


I have already almost implemented tests and releases with GitHub Actions in my another project, [requests-extra/requests-extra](https://github.com/requests-extra/requests-extra) so I will switch GitLabForm to it very soon.

**Comment by gdubicki** [comment]
@amimas : We did consider it, of course.

I personally like GitLab CI a lot, it's easy to understand, has great clean config syntax but is at the same time very powerful.

However it is a big decision to completely migrate to GitLab.com and I don't want to have the project being split into having code & issues here and CI elsewhere.

Also ...I wanted to have an excuse to try out GitHub Actions anyway. 😉

**Comment by gdubicki** [comment]
Phew, done. v.1.20.0 is the first version with the new CI complete.
