### ISSUE TITLE
Latest docker images not present on dockerhub

### ISSUE THREAD

**Issue by grzesuav** [egnyte/gitlabform#161]
https://hub.docker.com/r/egnyte/gitlabform/tags?page=1&ordering=last_updated

Do not see 1.19 images there

**Comment by gdubicki** [comment]
Yes, I know. We are migrating from Travis to GitHub Actions and building Docker images is _almost_ migrated.

This should be fixed within the next few days, I have been pretty busy recently...

**Comment by gdubicki** [comment]
Fixed with the v.1.20.0 release.
