### ISSUE TITLE
Project Audit Events are full of "Added protected branch"

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#178]
Probably because we unprotect and then protect branches again to perform some operations.

**Comment by nickshulba** [comment]
Hello Greg
Could you provide more details why Gitlabforms needs to do this protect/unprotect action against branch?
It caused my pipeline to fail turning off branch protection exactly when deploy started.
If this option is configurable, please give a hint. It would help me a lot if I could control this activity (or disable completely)

**Comment by sitnik** [comment]
This issue may actually break pipelines if they depend on protected variables and run at the same moment when protection was removed and not yet put back.
Why Renovate removes protection if nothing was changed in its and in repository configuration?

**Comment by gdubicki** [comment]
We do it to change the file values if you use the `files` configuration, for example. See https://github.com/egnyte/gitlabform/blob/main/gitlabform/gitlabform/processors/project/files_processor.py#L54-L59.

**Comment by YuraBeznos** [comment]
> We do it to change the file values if you use the files configuration, for example


Another place is in the branch processor: https://github.com/egnyte/gitlabform/blob/main/gitlabform/gitlabform/processors/project/branches_processor.py#L13

**Comment by YuraBeznos** [comment]
Interesting place: https://github.com/egnyte/gitlabform/blob/9908247e66b5c6cac47d1c147dbb9235e8aebd7a/gitlabform/gitlabform/processors/util/branch_protector.py#L37

Is it really required to unprotect first to change those values?

**Comment by gdubicki** [comment]
> Is it really required to unprotect first to change those values?

It was when I wrote that code.. Or I am not aware of some GitLab API feature? Something sudo-like? But was always using an admin token, so it should not be necessary..

**Comment by YuraBeznos** [comment]
> > Is it really required to unprotect first to change those values?
> 
> It was when I wrote that code.. Or I am not aware of some GitLab API feature? Something sudo-like? But was always using an admin token, so it should not be necessary..

Thanks! It looks like still required, but in most cases those settings are already set so this part in the code means lets rewrite the same thing which already set.

How about to check if settings are different first? I've tried to implement it via above MR but tests still require to be fixed.

**Comment by amimas** [comment]
> How about to check if settings are different first?

It'd be great if we could do that. Otherwise I find the audit events are becoming too noisy; not to mention the potential of CI breaking due to protected variables not being available when this is happening.

**Comment by YuraBeznos** [comment]
As I can see this one is fixed in latest releases of 2.x .

**Comment by gdubicki** [comment]
Yes, it should be completely fixed in v2.0.2+. Please reopen if anyone is still seeing this issue after GitLabForm upgrade.
