### ISSUE TITLE
Extra approval rules added in new groups

### ISSUE THREAD

**Issue by Pigueiras** [egnyte/gitlabform#180]
GitLab version 13.8.4
Gitlabform version: 1.20.2

I found out that when I create a new project and use a configuration to add merge approvals like this:

```
project_settings:
  "my_project":
    merge_requests:
      approvals:
        approvals_before_merge: 1
        reset_approvals_on_push: true
        disable_overriding_approvers_per_merge_request: true
        merge_requests_author_approval: false
      approver_groups:
        - my_group
```        

It adds an extra rule in the project and then it requires 2 approves to pass MRs

![image](https://user-images.githubusercontent.com/1941284/108539443-4e7d3000-72e0-11eb-9548-7f8a0f45fea1.png)

Debugging the issue it looks like the problem is in here: https://github.com/egnyte/gitlabform/blob/bcf4db607209b00845da39d22b668ec5c77f18f2/gitlabform/gitlabform/processors/project/merge_requests_processor.py#L18

If I try to reproduce the POST requests in a new project that Gitlabform is doing I get this:

```
$ curl -XGET -H 'Content-Type: application/json' --header "Authorization: Bearer ..." https://xxx/api/v4/projects/107/approval_rules
[]
$ curl -XGET -H 'Content-Type: application/json' --header "Authorization: Bearer ..." https://xxx/api/v4/projects/107/approvals
{"approvers":[],"approver_groups":[],"approvals_before_merge":0,"reset_approvals_on_push":true,"disable_overriding_approvers_per_merge_request":null,"merge_requests_author_approval":null,"merge_requests_disable_committers_approval":null,"require_password_to_approve":null}
# Now if you try to put new rules for the approvals
$ curl -XPOST -H 'Content-Type: application/json' --header "Authorization: Bearer ..." https://xxx/api/v4/projects/107/approvals -d '{"approvals_before_merge": 1, "disable_overriding_approvers_per_merge_request": true, "id": "107",merge_requests_author_approval": false, "reset_approvals_on_push": true}'
# You get the extra rule!
$ curl -XGET -H 'Content-Type: application/json' --header "Authorization: Bearer ..." https://xxx/api/v4/projects/107/approval_rules
[{"id":177,"name":"All Members","rule_type":"any_approver","eligible_approvers":[],"approvals_required":1,"users":[],"groups":[],"contains_hidden_groups":false,"protected_branches":[]}]
```

I tried to run the integration tests but my computer is too slow to run, if I have some time I'll try to test this in a VM some time later, but I'm not sure why this is not failing in your integration tests because you're explicitly checking in the tests the number of rules set by the API.

**Comment by Pigueiras** [comment]
I fixed it locally with this: https://github.com/egnyte/gitlabform/pull/181 but not sure if this is the behaviour you want because it overrides any other approval rule it may exist before in the project.

**Comment by gdubicki** [comment]
Hey @Pigueiras ! Thanks for reporting this.

The GitLab version we are using and testing on is Starter, so it doesn't support multiple approval rules at all ([you need a Premium plan for that](https://docs.gitlab.com/ee/user/project/merge_requests/merge_request_approvals.html#multiple-approval-rules)). Perhaps this is why we haven't noticed this issue before...

The short term fix could be merging #181 which we can do quickly, just after you add a feature flag and make this disabled by default to prevent unexpected breakage with a minor Gitlabform update as this would go out in v. 1.21.

The long term is to get a Premium license from GitLab for testing this app only.. Which is doable but GitLab "strongly suggest" moving the project itself to GitLab.com when joining their developers program to get such license, which we don't want to do as of now. :(

**Comment by Pigueiras** [comment]
Great! Would a flag like this would work for you or do you have something else in mind? 

```
... 
merge_requests:
      overwrite: true  <--- something like this? 
      approvals:
        approvals_before_merge: 2
        reset_approvals_on_push: true
        disable_overriding_approvers_per_merge_request: true
      approvers:
        - user1
        - user2
      approver_groups:
        - my-group
        - my-group1/subgroup
        - my-group2/subgroup/subsubgroup
```

**Comment by gdubicki** [comment]
I think that this would be a bit ambiguous.. How about a pretty long but self-explanatory "remove_other_approval_rules"?
