### ISSUE TITLE
Ability to set default branch?

### ISSUE THREAD

**Issue by llamasoft** [egnyte/gitlabform#182]
Maybe I missed it, but is there a way to have gitlabform set the default branch for a repository?  
We created new "main"/"develop" branches in many of our repositories, but the default branch still points to "master".  Being able to update the default branch from gitlabform would make it considerably easier to automate these changes.

**Comment by Pigueiras** [comment]
This one is working for me:

```
project_settings:
  default_branch: production
```

**Comment by llamasoft** [comment]
Odd, I'm not seeing that setting anywhere in the code or the example config.

**Comment by llamasoft** [comment]
Ahh, disregard.  I see it falls under `project_settings` which has a link to the available values.  I'll open a quick PR to add `default_branch` to the example config as it's a setting some people might be looking for.

**Comment by gdubicki** [comment]
I assume that this is fixed by #183. Please reopen if needed. :)
