### ISSUE TITLE
GitLab in Docker starts to throw HTTP 500 after a while

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#196]
I want to share this issue here first before I report it to GitLab to learn if any of you encountered the same thing.

I have been having problems with running tests on local GitLab in a Docker container for a while now.

Regardless of the GitLab version (I tried older `13.7.1-ee.0` as well as current latest `13.11.1-ee.0`) after a while GitLab starts throwing HTTP 500.

The reason for that seem to be file ownership problem, as Postgres starts to report that it cannot access some of its files. Excerpts from its log:
```
2021-04-27_16:33:10.16215 WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
```
(TODO: add more error messages)

When I opened bash in the container and checked those file it turned out that they are owned by root with mode 600 so that's why Postgres gitlab-psql user cannot access them:
```
root@gitlab:/# ls -la /var/opt/gitlab/postgresql/data/pg_stat_tmp/
total 32
drwx------  6 gitlab-psql gitlab-psql   192 Apr 27 14:31 .
drwx------ 29 gitlab-psql gitlab-psql   928 Apr 27 14:25 ..
-rw-------  1 root        root         1526 Apr 27 14:31 db_0.stat
-rw-------  1 gitlab-psql gitlab-psql  5751 Apr 27 14:23 db_1.stat
-rw-------  1 root        root        13525 Apr 27 14:31 db_16386.stat
-rw-------  1 gitlab-psql gitlab-psql   639 Apr 27 14:31 global.stat
```

I tried following https://docs.gitlab.com/omnibus/docker/README.html#permission-problems (although it does not seem right as I had this problem on a very fresh GitLab instance, not upgraded from a previous version) but some time after container restart those files started to be owned by root again.

I checked that Postgres processes are run by gitlab-psql user in the container, so I see no obvious reason for all of these to happen...

I am using macOS Big Sur (11.2.3 (20D91)) and Docker for Mac 3.3.1 (63152) (Docker Enginer: 20.10.5) but I notices some 500s in the GitHub Actions test runs, f.e. https://github.com/egnyte/gitlabform/actions/runs/790297758 , but haven't yet verified if these have the same root cause.

@ss7548 @YuraBeznos @mcjffld @poffey21 @Pigueiras as authors of recent PRs: have you encountered this?

**Comment by Pigueiras** [comment]
Sorry I can't help with this, I was executing the integration tests against a real GitLab dev instance because I couldn't manage to run GitLab in my laptop.

**Comment by ss7548** [comment]
I also run tests in my dev instance and have not encountered this issue.  I looked at my prod instance and all permissions are correct.  I am running 13.9.2

**Comment by gdubicki** [comment]
I think I got it fixed in v2 RC3.
