### ISSUE TITLE
Release pre-releases as a Docker image too

### ISSUE THREAD

**Issue by gdubicki** [egnyte/gitlabform#201]
It just hit me that if we only don't add a tag "latest" to a pre-release Docker image, then it will be effectively like a PyPI pre-release package - people using version "latest" will keep using the latest final while people interested in pre-releases will install them by pointing to their exact versions.

**Comment by weakcamel** [comment]
As I'm reading it (and  looking at [dev/build_docker_images.sh](https://github.com/egnyte/gitlabform/blob/main/dev/build_docker_images.sh) ) - this means just not building the `latest` and `<distro>-latest` tags?

**Comment by gdubicki** [comment]
Effectively yes, @weakcamel .

**Comment by gdubicki** [comment]
It works like a charm, @weakcamel . :) See the first pre-release with a Docker image - v2.0.0 RC5.

**Comment by weakcamel** [comment]
Yay, glad to hear that! :-)
