### ISSUE TITLE
Integration tests failing for v1.23.0 and Gitlab 13.11.3-ee locally

### ISSUE THREAD

**Issue by robin-moss** [egnyte/gitlabform#205]
**Describe the bug**

I'm trying to run the integration tests locally but almost every single test is failing. I noticed in the services tests that `hipchat` was returning `None` which is, in turn, is causing the tests to fail

Trying with Gitlab 13.10.0-ee.0 I get the same failures, so it doesn't appear to be a issue with me using the latest GitLab.

Any suggestion on what could be causing these failures?

**GitLabForm version**

gitlabform: Tag v1.23.0
GitLab: 13.11.3-33

**Comment by gdubicki** [comment]
Hi @robin-moss !

We will release v2 of the app very soon, with revamped tests so we don’t want to put effort into v1 tests anymore.

Can you please try running tests from the v2 branch?

**Comment by robin-moss** [comment]
The tests work fine on V2 :)
