### ISSUE TITLE
Running and colors issues on Windows

### ISSUE THREAD

**Issue by wolframhaussig** [egnyte/gitlabform#206]
**Describe the bug**
Hi, I stumbled over your project and as I want to try it out I figured I could just use the latest V2 release canditate. So I installed Python (Python 3.8.10) and used `pip install gitlabform==2.0.0rc3` to install gitlabform. I have 2 separate problems:
1. if I call `gitlabform` in Windows CMD or powershell it does not work because windows does not recognise the missing file ending. CMD or powershell requires `python C:\Users\[redacted]\AppData\Local\Programs\Python\Python38\Scripts\gitlabform -V`.
2. if I call `gitlabform -V` in the git bash the program works but it does not correctly output the colors:
![image](https://user-images.githubusercontent.com/13997737/117657528-f399fd00-b199-11eb-979c-cf7a0f09f727.png)

It would be great if the script would either work from CMD/Powershell also or that a recommandation for using git bash or something similar is mentioned.
Also, is there a way to make the color output work on windows or at least do not show it on windows as the escape sequences make it hard to read?

**GitLabForm version**: v2.0.0rc3

Output of `gitlabform -V`:
```
[0m GitLabForm version: [34m2.0.0rc3 [0m[0m = pre-release  (the latest stable is [34m1.23.0[0m)
```

**Comment by gdubicki** [comment]
Hey @wolframhaussig ! Thanks for trying out this app. :)

I will try to get these issue fixed but frankly as I don’t have a proper Windows workstation available it may take me a while, so PRs for this are very welcome.

Btw: did you have any issues after you actually started the app, did it work?

**Comment by wolframhaussig** [comment]
@gdubicki I would be happy to help with this but I am not a python programmer so I would not know where to start so I have to rely on someone with Python knowledge.

After the app started it seems to work(could connect to Gitlab, parsed my config file and all) but I have not done anything big with it yet - it looks promising though.

**Comment by gdubicki** [comment]
It was too interesting to just leave it as it is 😅 , so I installed Python on my gaming PC and release v2.0.0rc5 that should fix both issues.

Please check it out and let me know how it works for you, @wolframhaussig . :)

**Comment by gdubicki** [comment]
v2 final has been released. Please reopen this ticket if you still have issues under Windows, @wolframhaussig .

**Comment by wolframhaussig** [comment]
@gdubicki Sorry for the late response - I was on vacation last week. I have just downloaded the latest version and it looks great. Thank you!
