### ISSUE TITLE
Gitlab 10.3 compatibility

### ISSUE THREAD

**Issue by staticdev** [egnyte/gitlabform#22]
Is there any plans to support Gitlab 10.3?

**Comment by gdubicki** [comment]
While I haven't yet tested GitLabForm with GitLab 10.3 (or 10.4, released today) there is no reason for it not to work.

We will only have to migrate to API v4 before release of GitLab 11, but there's already a ticket for that here: #1 

I update README to take this into account.

So please go ahead and use GitLabForm! In case of any specific issues please let me know.
