### ISSUE TITLE
gitlab api requests to push_rules fails if there're a dot in a project or group name

### ISSUE THREAD

**Issue by YuraBeznos** [egnyte/gitlabform#224]
Gitlab api requests to push_rules fails if there're a dot in a project or group name.
So when get will fail, post will also fail because of empty value from get and post might be used only to create a new settings, but put must be used to update them.

https://github.com/egnyte/gitlabform/blob/56c9f73e4ebc533e4cc9843c82fe792f5121b0d2/gitlabform/gitlab/projects.py#L229

Looks like id must be used in general for gitlab api requests.

**Comment by gdubicki** [comment]
Thanks for reporting this @YuraBeznos !

This should be fixed in v2.0.4 released a moment ago. Please reopen this issue if you are still seeing the issue after GitLabForm upgrade.
