### ISSUE TITLE
Add option to allow push force in protected branches

### ISSUE THREAD

**Issue by Pigueiras** [egnyte/gitlabform#227]
There is no way to specify `allow_force_push` when setting up the protected branches

https://docs.gitlab.com/ee/api/protected_branches.html#protect-repository-branches

**Comment by gdubicki** [comment]
I think that we should start [passing raw parameters](https://github.com/egnyte/gitlabform/blob/main/docs/FEATURES_DESIGN.md#raw-parameters-passing) for protected branches.

If we want to keep the backward compatibility (= not release v3 already) we can do it when we detect `push_access_level` or `merge_access_level` or `unprotect_access_level` set.

Then we would have this feature future-proof like project settings is.

I would be happy to accept a PR with this. :)

**Comment by gdubicki** [comment]
Oops, actually this is not yet implemented.. 😅
