### ISSUE TITLE
GitLab in Docker fails to start properly when running acceptance tests

### ISSUE THREAD

**Issue by andrewjw** [egnyte/gitlabform#229]
Hi,

I have a change which I think resolves [#150](https://github.com/egnyte/gitlabform/issues/150). I've tested it against our GitLab instance, and it works, but I wanted to write some acceptance tests before submitting it. However, I'm having trouble running GitLab in Docker so I can run the tests. Even after leaving `./dev/run_gitlab_in_docker.sh` running for over an hour it doesn't complete.

I presume you're reusing something provided by GitLab, but could you share what sort of machine you run the docker container on? How much memory does it need to run reasonably well? Unfortunately I'm not comfortable running the acceptance tests against our own GitLab instance.

In case it's useful, here are some log lines from the container:
```
==> /var/log/gitlab/gitlab-rails/production.log <==
Started GET "/" for 127.0.0.1 at 2021-06-01 15:50:25 +0000

==> /var/log/gitlab/gitaly/current <==
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-06-01T15:50:30.342Z","worker.name":"gitaly-ruby.0"}
{"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded","level":"warning","msg":"gitaly-ruby worker health check failed","time":"2021-06-01T15:50:34.835Z","worker.name":"gitaly-ruby.1"}

==> /var/log/gitlab/gitlab-rails/application.log <==
2021-06-01T15:50:34.855Z: ActiveRecord connection established

==> /var/log/gitlab/gitlab-rails/application_json.log <==
{"severity":"DEBUG","time":"2021-06-01T15:50:34.857Z","correlation_id":null,"message":"ActiveRecord connection established"}

==> /var/log/gitlab/gitlab-workhorse/current <==
{"correlation_id":"01F7449GBN0BB2P1EC7B1AHZHN","duration_ms":14812,"error":"badgateway: failed to receive response: EOF","level":"error","method":"GET","msg":"","time":"2021-06-01T15:50:34Z","uri":"/"}

==> /var/log/gitlab/puma/puma_stdout.log <==
{"timestamp":"2021-06-01T15:50:34.873Z","pid":370,"message":"- Worker 0 (PID: 1481) booted, phase: 0"}
```

Thanks,
Andrew

**Comment by gdubicki** [comment]
Hi @andrewjw !

Are you by any chance trying to run it on an M1 Mac? Because GitLab doesn't start on such for me too, see https://forum.gitlab.com/t/gitlab-ce-docker-on-apple-m1-stuck-on-recipe-gitlab-database-migrations/49297 .

I have been running that script successfully on an Intel CPU Macbook Pro with 32GB of RAM.

**Comment by andrewjw** [comment]
Hi Greg,

Sadly I don't have a fancy M1 Mac yet :-) It is an Intel Macbook Pro, but I only have 16GB of RAM, so maybe the lack of RAM is the problem. It would be interesting to know if anyone has got it to work with 16GB, but I will see if I can get an 32GB AWS instance to run it on, and fingers crossed that'll work.

Thanks,
Andrew

**Comment by gdubicki** [comment]
I have the following resources provided to Docker on that Macbook: 1 CPU, 8GB RAM, 512MB swap, 64GB disk.

You can also try running the exact image version I am successfully running right now, like this: `./dev/run_gitlab_in_docker.sh 13.12.1-ee.0` - maybe a newer one has some new issues...

**Comment by andrewjw** [comment]
Ah, I had forgotten about the Docker VM. I had it set to only 2GB of RAM. Increasing that to 4GB let GitLab launch successfully and I can run the tests ok. 8GB also worked, but allocated 50% of my RAM to Docker seems a bit much.

Thanks for your help. Hopefully I'll be back with pull request soon.

Cheers,
Andrew
