### ISSUE TITLE
Can't find config.yml

### ISSUE THREAD

**Issue by nomadme** [egnyte/gitlabform#23]
All my setups are according to the documentation, yet, it fails to find the config.yml.

    ➜  gitlab pwd
    /Users/Nomadme/Projects/Code/gitlab
    ➜  gitlab ll
    total 8
    drwxr-xr-x   3 Nomadme  staff  102 Jan 29 10:15 ./
    drwxr-xr-x  27 Nomadme  staff  918 Jan 29 09:49 ../
    -rw-r--r--   1 Nomadme  staff  974 Jan 29 10:14 config.yml
    ➜  gitlab gitlabform ALL
    Aborting - config file not found at: /Users/Nomadme/Projects/Code/gitlab/config.yml

**Comment by gdubicki** [comment]
Hi @nomadme ! Sorry for a late reply.

Please provide the following info:

Your OS and version

Outputs of:
```
python --version
pip3 --version
gitlabform --version
```

Can you also try providing the config path explicitly with `gitlabform -c /Users/Nomadme/Projects/Code/gitlab/config.yml ALL`?

**Comment by nomadme** [comment]
@gdubicki Thanks for getting back with me.

This is the versions I'm running under.
    
    ➜  gitlab_form python --version
    Python 2.7.10
    ➜  gitlab_form pip3 --version
    pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
    ➜  gitlab_form gitlabform --version
    usage: gitlabform [-h] [-c CONFIG] [-v | -d] [--strict]
                  [--start-from START_FROM] [-n]
                  project_or_group
    gitlabform: error: the following arguments are required: project_or_group
    ➜  gitlab_form gitlabform -c /Users/Nomadme/Projects/Code/gitlab_form/config.yml ALL
    Aborting - config file not found at: /Users/Nomadme/Projects/Code/gitlab_form/config.yml

**Comment by gdubicki** [comment]
Ok, that doesn't really help me. :) Let's move with this to our newly open gitter chat room, ok? -> https://gitter.im/egnyte/gitlabform

(Of course I will post results here for future reference, if that will make sense)

**Comment by nomadme** [comment]
fresh install of python3 and pip3 did the trick.

**Comment by nomadme** [comment]
OK, I re-pulled this repo and now the `gitlabform` can't find the config.yml again.
```
gitlabform git:(master) ✗ pip3 list
Package    Version
---------- ---------
certifi    2018.4.16
chardet    3.0.4
gitlabform 0.23.0.2
idna       2.6
pip        18.0
PyYAML     3.12
requests   2.18.4
setuptools 28.8.0
urllib3    1.22
➜  gitlabform git:(master) ✗ python -V
Python 3.5.5

gitlabform git:(master) ✗ gitlabform ALL
Aborting - config file not found at: /Users/Nomadme/Projects/code/deploy_gitlab/gitlabform/gitlabform/gitlabform/config.yml
```

**Comment by nomadme** [comment]
Ok, never mind, got it working, but API v3 is no longer supported 😝
