### ISSUE TITLE
Managing project members is incredible slow

### ISSUE THREAD

**Issue by andrewjw** [egnyte/gitlabform#240]
While managing project group members works, it is incredibly slow because the check that detects whether group access needs updating doesn't work, and groups are removed and readded on every run.

The issue is that the `get_groups_from_project` API call returns a dictionary keyed on group name, but the `members/groups` uses group path. (This existed in master currently)

A PR for this is incoming...

Thanks,
Andrew Wilkinson (on behalf of Ocado Technology)

**Comment by gdubicki** [comment]
Thank you for reporting and for the fix @andrewjw ! v2.1.2 with this has just been released.
