### ISSUE TITLE
Add configuration for Merge Request squash option

### ISSUE THREAD

**Issue by tyronedd** [egnyte/gitlabform#243]
With the [Merge Request](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/66122) merged and released in 14.1 the projects API now exposes the `squash_option`:

![image](https://user-images.githubusercontent.com/17970041/126873226-724c33fa-7c1d-496f-bc60-d8bbc8c2ff94.png)

https://docs.gitlab.com/ee/api/projects.html#create-project

I'd like to able to configure this with GitLabForm.

Thanks!

**Comment by tyronedd** [comment]
Ahhh, following a comment on another issue I found this:

https://github.com/egnyte/gitlabform/blob/main/docs/FEATURES_DESIGN.md#raw-parameters-passing

So I think this should already be possible automatically.

**Comment by gdubicki** [comment]
Exactly, it should, @tyronedd . As long as you have new enough GitLab version, of course.

Please feel free to reopen this issue if it doesn't work for you for any reason.
