### ISSUE TITLE
Support for project-level approvals (Gitlab 10.6 EE)

### ISSUE THREAD

**Issue by born4new** [egnyte/gitlabform#26]
Hi guys,

Would it be possible to add the following resource to the tool? `POST /projects/:id/approvals`

[Gitlab API Documentation](https://docs.gitlab.com/ee/api/merge_request_approvals.html)

Potential problem: It is only available to `EE starter` and above. Not sure how you handle this in the tool...

Let me know if I can be of any help! I am not very familiar with Python, but I'm sure I could make something work.

Cheers!

**Comment by born4new** [comment]
Any thoughts?

**Comment by gdubicki** [comment]
Hi @born4new ,

We will definitely add this feature to gitlabform as we have been waiting for a long time for this GitLab API feature.

But I can't give you exact date when this will be ready.

I will let you know about progress in this ticket.

Thanks,
Greg

**Comment by gdubicki** [comment]
Implemented in 0.23.0 released a moment ago.

I have "handled" that this feature requires 10.6 EE by mentioning it in the README. ;P

**Comment by gdubicki** [comment]
Let me know if it works for you, @born4new !

**Comment by born4new** [comment]
Works like a charm @gdubicki, thanks a lot!
