### ISSUE TITLE
Support configurable commit message for file operations

### ISSUE THREAD

**Issue by aleung** [egnyte/gitlabform#278]
GitLabForm generates commit message for file new/update/delete operation:

https://github.com/egnyte/gitlabform/blob/ab7b8da4410767dd93713ceedddd1d5d0737edbe/gitlabform/gitlabform/processors/project/files_processor.py#L191

Our GitLab has hook configured to validate commit message format. Any commit which doesn't follow the pattern is rejected. Configurable commit message is needed in this use case.

**Comment by gdubicki** [comment]
Thanks for the suggestion @aleung !

It should be very easy to make the app read the commit message from a field in the configuration file.

PRs with this feature are welcome, as usual! ☺️

**Comment by gdubicki** [comment]
Thanks for you contribution @aleung ! I will release a new version with your new feature in a day or two.
