### ISSUE TITLE
Changing group level default branch setting fails if underlying projects don't have the branch

### ISSUE THREAD

**Issue by rossbeehler** [egnyte/gitlabform#366]
When trying to change `project_settings`-->`default_branch` at the group level, gitlabform attempts to apply the setting to existing projects in that group, which will fail for any project that doesn't have that branch, including empty projects just created.  Is there a way to just apply that setting to the group?

Steps to recreate:
* create an empty project with no commits/branches
* run gitlabform to change the `default_branch` of the group with the empty project
* receive an error like the following:

Request url='https://gitlab.com/api/v4/projects/some-group%2Fsome-project', method=PUT, json='{"default_branch": "master"}' failed - expected code(s) [200], got code 400 & body: '{"message":{"base":["Could not change HEAD: branch 'master' does not exist"]}}'

**Comment by rossbeehler** [comment]
I think there was a miscommunication on our side, as we thought gitlabform was changing the "Initial default branch name" setting on the group (found under Settings --> Repository --> Default branch), but, as you pointed out, that's not even possible in the API.  Sorry for the confusion.

**Comment by amimas** [comment]
Sounds good. Glad it's clear now. Hope it works out for you.
