### ISSUE TITLE
Configure Slack notifications 

### ISSUE THREAD

**Issue by edbizarro** [egnyte/gitlabform#4]
How do I configure Slack notifications?

```yaml
services:
  slack:
    webhook: "url"
    username: "username"
```

**Comment by gdubicki** [comment]
Hey @edbizarro! Sorry for a late reply, thanks for trying out gitlabform and filing the first not-created-by-me ticket. ;)

As gitlabform makes PUTs with data from the given services hash, if https://docs.gitlab.com/ce/api/services.html#create-edit-slack-service is telling us the truth, then your config should work.

To test it you can first limit gitlabform run to a single project with: gitlabform your_project_group/your_project

Please let me know if it helped!

**Comment by gdubicki** [comment]
I have just tested it and it should work. But it requires the "url" to be a working slack webhook url at the time service is being enabled, otherwise you will get 400 from GitLab. So trying it out with some example url won't work.

**Comment by edbizarro** [comment]
Great!

This tool is really helpful, my company has ~20 repos in gitlab.com and changing settings one by one is frustrating.

Tks for your help.

**Comment by gdubicki** [comment]
I am happy to hear that. :) In case of any other problems please check out the improved docs in example config.yml that I have updated today.

**Comment by gdubicki** [comment]
I and closing this issue as I assume that you have used gitlabform successfully, @edbizarro. Please reopen if you still have questions about this.
