### ISSUE TITLE
Handle groups settings

### ISSUE THREAD

**Issue by ghost** [egnyte/gitlabform#58]
Gitlab has some settings for a group themselves. However, when I try to set up some hook with **gitlab-conf**, settings are applied for project under the group instead. To be specific, a webhook can be installed at group level, or project level; however specifying hook under `groups_settings` will deploy the hook for every project under the group. 

Relevant source: https://github.com/egnyte/gitlabform/blob/73acba82990655247c8fc5d5be84864ccf792a50/gitlabform/gitlabform/core.py#L210 : there isn't setting for group themselves.

**Comment by SilverXXX** [comment]
Made pr #60 to try and add this feature

**Comment by gdubicki** [comment]
I have just reviewed #60. If we get this merged then adding more group-level settings will be easy. I can't promise that but I may implement it soon.

Thanks for the idea, @ghost, and for the PR, @SilverXXX !

**Comment by gdubicki** [comment]
Version 1.6.0 with group-level secret variables management released. A PR for adding group-level hooks management is welcome!

**Comment by gdubicki** [comment]
Added in 1.9.0 released today. Please open a new ticket if you find any bugs!
