### ISSUE TITLE
Implement badges endpoint

### ISSUE THREAD

**Issue by RoamingKiwi** [egnyte/gitlabform#59]
It's a small thing but I would find this useful. E.g. I want to add a badge so people know the project is managed by gitlabform.

Project badges are managed under this endpoint https://docs.gitlab.com/ee/api/project_badges.html
Group badges use this one https://docs.gitlab.com/ee/api/group_badges.html

**Comment by glensc** [comment]
@gdubicki Could this be as simple as https://github.com/egnyte/gitlabform/pull/144?

**Comment by glensc** [comment]
OK, seems not as there are different endpoints:
- https://docs.gitlab.com/ee/api/project_badges.html
- https://docs.gitlab.com/ee/api/group_badges.html

**Comment by gdubicki** [comment]
Implemented in v2.2.0, released a moment ago.
