### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by veraciousnottaken** [egnyte/gitlabform#63]
I'm using GitLab CE 12.3.1 with self signed certificate placed under /etc/gitlab/trusted-certs

When I try `gitlabform ALL` i get:

> Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /api/v4/version
Aborting -

**Comment by gdubicki** [comment]
Hi @veraciousnottaken ! Please update to gitlabform >= 1.7.0 and set `ssl_verify: true` in `gitlab` section of the config (see example `config.yml`).
