### ISSUE TITLE
CI / CD schedules

### ISSUE THREAD

**Issue by ginkel** [egnyte/gitlabform#66]
This is more of a feature request. I came across this project while looking for tools that I could use to automatically manage the CI / CD schedules within a GitLab instance. AFAICS `gitlabform` currently does not support this, but IMHO it would fit in very well.

The API is documented at: https://docs.gitlab.com/ee/api/pipeline_schedules.html

**Comment by gdubicki** [comment]
Implemented in #130, released in v. v1.18.0.
