### ISSUE TITLE
Protecting branches with wildcards doesn't work with 1.15.1

### ISSUE THREAD

**Issue by ochosi** [egnyte/gitlabform#98]
Hi, seemingly there were some recent changes to branch protections.
I tried to use gitlabform to protect wildcard branches, in our case "xfce-*".

As a response I get this
`+++ Error while processing 'test-group/test-repo1'
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/gitlabform/gitlabform/core.py", line 270, in process_all
    self.process_branches(project_and_group, configuration)
  File "/home/user/.local/lib/python3.7/site-packages/gitlabform/gitlabform/core.py", line 40, in method_wrapper
    return method(self, project_and_group, configuration)
  File "/home/user/.local/lib/python3.7/site-packages/gitlabform/gitlabform/core.py", line 513, in process_branches
    self._protect_branch(project_and_group, configuration, branch)
  File "/home/user/.local/lib/python3.7/site-packages/gitlabform/gitlabform/core.py", line 524, in _protect_branch
    configuration['branches'][branch]['developers_can_merge'])
  File "/home/user/.local/lib/python3.7/site-packages/gitlabform/gitlab/branches.py", line 16, in protect_branch
    expected_codes=[200, 201])
  File "/home/user/.local/lib/python3.7/site-packages/gitlabform/gitlab/core.py", line 114, in _make_requests_to_api
    response = self._make_request_to_api(path_as_format_string, args, method, data, expected_codes, json)
  File "/home/user/.local/lib/python3.7/site-packages/gitlabform/gitlab/core.py", line 172, in _make_request_to_api
    response.status_code)
gitlabform.gitlab.core.UnexpectedResponseException: Request url='https://gitlab.example.com/api/v4/projects/test-group%2Ftest-repo1/repository/branches/xfce-%2A/protect', method=PUT, data='{'id': 'test-group/test-repo1', 'branch': 'xfce-*', 'developers_can_push': False, 'developers_can_merge': False}' failed - expected code(s) [200, 201], got code 400 & body: 'b'{"message":"The branch refname is invalid"}''`

**Comment by wadimklincov** [comment]
How did you configure it? See [here](https://github.com/egnyte/gitlabform/blob/master/config.yml#L150) for an example.

**Comment by ochosi** [comment]
I followed exactly this example. I can post a minimal reproducer/config from my side if that helps

**Comment by ochosi** [comment]
Relevant part of the code I tried (the config for "master" worked, the part for "xfce-*" didn't with the error output above).

>     # master and xfce-* branches are protected, only maintainers can merge/push
    branches:
      master:
        protected: true
        developers_can_push: false
        developers_can_merge: false
      "xfce-*":
        protected: true
        developers_can_push: false
        developers_can_merge: false

**Comment by wadimklincov** [comment]
This uses the old endpoint of declaring protected branches and as far as I know it didn't support wildcards in branch names. How about something like this:

```yaml
branches:
  master:
    protected: true
    developers_can_push: false
    developers_can_merge: false
  "xfce-*":
    protected: true
    push_access_level: 40
    merge_access_level: 40
    unprotect_access_level: 40
```

**Comment by ochosi** [comment]
Darn, I could swear I tried that yesterday as well (I was already quite desperate)...

So that worked - THANKS @wadimklincov !
(Maybe update the config.yml in this repo to reflect the new API only ;))

**Comment by gdubicki** [comment]
Thanks for raising the issue and sorry that you had problems with GitLabForm, @ochosi ! I have updated the example `config.yml` by adding this warning https://github.com/egnyte/gitlabform/blob/master/config.yml#L150 but I kept the examples using old syntax. I find them easier to understand as they resemble the web UI and are good enough for many use cases.
